# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

export ZSH_THEME="amuse"

# Reset PATH and add system bins to path
export PATH="/bin:/sbin:/usr/bin:/usr/sbin"

# Add homebrew bins to PATH
export PATH="$PATH:/usr/local/bin"

# Set nvim as default editor
export EDITOR='nvim'
