source $ZSH/oh-my-zsh.sh

# rbenv
# To enable shims and autocompletion add to your profile:
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

### PATH MODIFICATIONS ########################
#
# These PATH modification are only for use with interactive shells.

# Add local folder binstubs to path
export PATH="./bin:$PATH"

### PATH MODIFICATIONS ########################

# Homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

# Autojump
[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

# pyenv & pyenv-virtualenv
# To enable shims and autocompletion add to your profile:
# https://github.com/pyenv/pyenv#basic-github-checkout
if which pyenv > /dev/null; then eval "$(pyenv init --path)"; fi
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi

alias b=bundle exec

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
