source $ZSH/oh-my-zsh.sh

### PATH MODIFICATIONS ########################
#
# These PATH modification are only for use with interactive shells.

# Add brew's coreutils to path
export PATH="$PATH:~/bin"

# export PATH=$(brew --prefix coreutils)/libexec/gnubin:$PATH

#
### PATH MODIFICATIONS ########################

# Homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

# Autojump
[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

# rbenv
# To enable shims and autocompletion add to your profile:
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# Add local folder binstubs to path
export PATH="./bin:$PATH"

# pyenv & pyenv-virtualenv
# To enable shims and autocompletion add to your profile:
# https://github.com/pyenv/pyenv#basic-github-checkout
if which pyenv > /dev/null; then eval "$(pyenv init --path)"; fi
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi

alias b=bundle exec

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

